2025-07-09 15:26:55,763 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:26:55.762852+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:26:55,764 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:26:55,767 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:26:55.767201+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:26:55,768 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:26:55,771 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-07-09T15:26:55.771494+02:00"}"
>
2025-07-09 15:26:55,773 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:26:55,775 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:26:55.775429+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:29:46,194 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:29:52,853 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:29:53,746 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:29:54,536 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:30:18,755 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:18,758 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:30:18.757899+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:30:46,938 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:30:46,940 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 15:30:46,945 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,950 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,954 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,958 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,962 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,966 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,970 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,974 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,978 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:46,982 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:51,989 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:51,994 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:51,999 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,003 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,007 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,012 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,016 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,020 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:52,024 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,032 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,036 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,040 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,044 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,048 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,052 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,056 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,060 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:30:57,064 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,069 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:31:02.06914+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:31:02,073 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,077 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,081 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,085 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,089 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,093 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,096 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:31:02,101 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:33:17,639 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:18,144 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:18,474 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:18,695 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:18,880 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:19,067 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:19,252 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:55,450 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:33:56,200 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:34:09,550 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:34:09,552 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 15:34:09,557 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,561 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,565 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,569 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,573 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,577 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,581 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,585 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,590 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:09,593 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,601 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:34:14.60119+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:34:14,605 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,609 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,613 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,617 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,621 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,625 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,629 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:34:14,633 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:35:10,265 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:35:10,265 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 15:35:40,959 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:35:40,960 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 15:36:23,525 [DEBUG] common.service: Connected to grpc server securely!
